### ISSUE TITLE
TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by NorthernMan54** [onlxltd/bonjour-service#47]
With version 1.2.0 we are getting this issue with Homebridge-config-ui-x

```
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at equalTxt (/opt/homebridge/lib/node_modules/homebridge-config-ui-x/node_modules/bonjour-service/src/lib/utils/equal-txt.ts:2:24)
    at Browser.updateService (/opt/homebridge/lib/node_modules/homebridge-config-ui-x/node_modules/bonjour-service/src/lib/browser.ts:145:21)
    at /opt/homebridge/lib/node_modules/homebridge-config-ui-x/node_modules/bonjour-service/src/lib/browser.ts:108:30
    at Array.forEach (<anonymous>)
    at /opt/homebridge/lib/node_modules/homebridge-config-ui-x/node_modules/bonjour-service/src/lib/browser.ts:106:25
    at Array.forEach (<anonymous>)
    at EventEmitter.onresponse (/opt/homebridge/lib/node_modules/homebridge-config-ui-x/node_modules/bonjour-service/src/lib/browser.ts:98:34)
    at EventEmitter.emit (node:events:514:28)
    at Socket.<anonymous> (/opt/homebridge/lib/node_modules/homebridge-config-ui-x/node_modules/multicast-dns/index.js:49:43)
    at Socket.emit (node:events:514:28)
    at UDP.onMessage (node:dgram:941:8)
```

We resolved by dropping back to version 1.1.1

https://github.com/homebridge/homebridge-config-ui-x/issues/1973
https://github.com/homebridge/homebridge-syno-spk/issues/145

**Comment by mdidon** [comment]
@NorthernMan54 Thanks for the heads up. I'll have at this.
Can you provide the initialisation code (or location of) for bonjour-service to test against.

**Comment by mdidon** [comment]
@NorthernMan54 I've been able to replicate the issue and have released a patch under v1.2.1.

**Comment by NorthernMan54** [comment]
Tks for quickly fixing this, much appreciated

**Comment by donavanbecker** [comment]
We have pushed this to a beta so once we get confirmation that this resolve the issue. We can let you know.

**Comment by donavanbecker** [comment]
Just got confirmation from a few testers and all is good. Thanks for the quick fix!

**Comment by mdidon** [comment]
@donavanbecker @NorthernMan54 Good to hear, I will mark as closed.
Many thanks
